### ISSUE TITLE
There are too many crabs

### ISSUE THREAD

**Issue by LimitXiaoHuoChai** [Jukoz/middle-earth#46]
Module author Hello, I like the dimension of Middle-earth world, but the number of crabs in this module is too much in the main world, I just wait for ten minutes at the beach, the number of crabs can reach hundreds, the computer will be stuck, there is no configuration file, I do not know how to modify, I am Chinese, English is not good, use machine translation.
![160136464983350078209](https://github.com/Jukoz/middle-earth/assets/141458306/507f58e8-bdfd-46ab-868a-5a845aa45bb4)

**Comment by Jukoz** [comment]
Fixed, thanks for opening this issue.
