### ISSUE TITLE
BUG feedback

### ISSUE THREAD

**Issue by LimitXiaoHuoChai** [Jukoz/middle-earth#48]
The new version of the Middle-earth world will make the sky stratified without opening the shader, the empty bottle formula of the starlight bottle Rei can not be searched, the crab is still the same for a long time to generate a particularly large number, the starlight bottle in the Middle-earth world can not return to the original world, I hope the author will fix it. Thanks a lot.
I am a Chinese, do not understand English, the above is from machine translation.

**Comment by Jukoz** [comment]
Hi, thanks for the bug report.
Why do you mean exactly by "The new version of the Middle-earth world will make the sky stratified without opening the shader"? Do you have incompatibilities with a shader mod?

For the rest, the crab is fixed, we just haven't published the new version on modrinth.
And we will make REI mod compatibility in future version aswell as a new way to exit Middle-earth.

**Comment by LimitXiaoHuoChai** [comment]
Thank you for the author's reply. Middle-earth is really great in this dimension.






Limit小火柴
***@***.***






---Original---
From: ***@***.***&gt;
Date: Fri, Oct 20, 2023 05:35 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Jukoz/middle-earth] BUG feedback (Issue #48)




 
Hi, thanks for the bug report.
 Why do you mean exactly by "The new version of the Middle-earth world will make the sky stratified without opening the shader"? Do you have incompatibilities with a shader mod?
 
For the rest, the crab is fixed, we just haven't published the new version on modrinth.
 And we will make REI mod compatibility in future version aswell as a new way to exit Middle-earth.
