### ISSUE TITLE
Hates Quilt.

### ISSUE THREAD

**Issue by MagmaBro123** [Jukoz/middle-earth#97]
No other mods are in use.

![image](https://github.com/Jukoz/middle-earth/assets/51277766/fcd84ff1-1d06-4ebe-ad8f-729074b77b80)

[crash-2024-03-22_21.35.41-client.txt](https://github.com/Jukoz/middle-earth/files/14730087/crash-2024-03-22_21.35.41-client.txt)

**Comment by Jukoz** [comment]
This mod is for Fabric api, not Quilt.

**Comment by MagmaBro123** [comment]
Quilt uses a fork of Fabric API.
